### ISSUE TITLE
Crucial P1 1TB SSD on MacBook Pro 13" (Mid 2014) A1502

### ISSUE THREAD

**Issue by ahmedeltawel** [kvic-z/SsdPmEnabler#11]
I’m running Big Sur, macbook pro 13’ mid 2014
I really wanted it to work as my battery had been draining so bad since i upgraded my ssd, I tried it a couple of times and Noticed that as soon as it hits 10 mAps it just freezes right away and that crashes and reboot the macbook

**Comment by ahmedeltawel** [comment]
And the adaptor is Sintech

**Comment by kvic-z** [comment]
FAQ: [Why are MacBookAir6,2 and MacBookPro11,1 not supported](https://github.com/kvic-z/SsdPmEnabler/wiki/FAQ#3-why-are-macbookair62-and-macbookpro111-not-supported)
