### ISSUE TITLE
Kernel panic with SsdPmEnabler on MacBook Pro 15" (Mid 2014) A1398 with Crucial P2 2TB SSD

### ISSUE THREAD

**Issue by porg** [kvic-z/SsdPmEnabler#12]
As reported in #3 power saving works fine for this model.
Now after 9 months with this SSD I experienced the first crash.

My Mac was unattended, playing music in Podcast.app through the amplifier via analog 3.5mm cable. Some other apps idle in the background. Suddenly the music stopped and when looking at the Mac I saw it rebooted to the error screen "[No startup disk found](https://support.apple.com/en-us/HT204323)" . I shut it down via long-press onto the power button. Next day started again, a dialog told me that my Mac did not shut down properly. Click any key to continue. Then it rebooted fine.

After startup the the Crash Reporter opened with the kernel log.  I checked System Info > Extensions: SsdPmEnabler was shown as loaded. It crash log mentions nvme. I do not know whether it was a hardware I/O issue or a driver issue of macOS.

Maybe it also has something to do with SsdPmEnabler?

Here is my log: [nvme Fatal error occurred.log](https://github.com/kvic-z/SsdPmEnabler/files/7134664/nvme.Fatal.error.occurred.log)

**Comment by kvic-z** [comment]
This crash should have nothing to do with ssdpmEnabler.

Perhaps a real bug climbed into and near the SSD socket. Perhaps your SSD/adaptor/socket decided to jiggle a bit and in poor contact when the crash happened. I would start worrying about it when it recurs often. Once a year? Forget about it..

Protips: always handle your MBP with both hands.

**Comment by porg** [comment]
Thanks for the answer. I then consider it as a random HW/FW issue which if happening 1-2/year is to be ignored.

P.S.: Why holding with both hands? To avoid bending stress on the case and PCB? Or to avoid slipping and bumping?

**Comment by kvic-z** [comment]
Primarily to avoid bending PCBs and loosening contact between SSD/adaptor/socket and resulting in a crash.
