### ISSUE TITLE
Big Sur 11.5.2@MacBook 2015 Mid Not work

### ISSUE THREAD

**Issue by GitBubble** [kvic-z/SsdPmEnabler#16]
SSD :  samsung 970 evo 1TB

**Comment by kvic-z** [comment]
Sorry, insufficient information to even start thinking of your problem.

If you get a MacBookPro11,1, then as indicated in [FAQ](https://github.com/kvic-z/SsdPmEnabler/wiki/FAQ#3-why-are-macbookair62-and-macbookpro111-not-supported), your Mac cannot cope with lower SSD power states.
