### ISSUE TITLE
Crash on Install

### ISSUE THREAD

**Issue by AdriandeLima** [kvic-z/SsdPmEnabler#17]
I'm using a MBP mid 2014, running Macos Moja

ve 10.14.6 lastest security patch. I'm using a Crucial P2, sintech adapter. When I install SsdPmEnabler, the mac will crash (and continue crashing), and I then have to uninstall it from the terminal in recovery mode (using your instructions on the main page.)
The point at which it crashes is when I rebuild the the kext cache :  sudo kextcache -i /
The terminal showed the error message "locked, waiting for lock" before crashing, leaving a generic crash error message (your mac has c
Here is the only log created on the crash, which is probably irrelevant because it creates one of these every time I restart/shutdown.
[spindump.txt](https://github.com/kvic-z/SsdPmEnabler/files/7655704/spindump.txt)

Also to note, I have Lilu and NVMEFix installed aswell, but I'm pretty sure SsdPmEnabler crashed the mac before I installed them.

**Comment by kvic-z** [comment]
Your spindump.txt indicates you're using a MacBookPro11,1. This model cannot cope with 3rd party NVMe SSD in lower power mode as stated clearly in the [FAQ](https://github.com/kvic-z/SsdPmEnabler/wiki/FAQ#3-why-are-macbookair62-and-macbookpro111-not-supported).
