### ISSUE TITLE
Apple Silicon (`arm64e`) support

### ISSUE THREAD

**Issue by wimleers** [kvic-z/SsdPmEnabler#20]
# What I tried so far
After trying and retrying the installation steps listed in https://github.com/kvic-z/SsdPmEnabler numerous times, reading the [FAQ](https://github.com/kvic-z/SsdPmEnabler/wiki/FAQ), following the [Apple silicon-specific instructions to allow unsigned KEXTs](https://support.apple.com/en-gb/HT210999) (also available in [more elaborate form](https://support.apple.com/en-gb/guide/mac-help/mchl768f7291/mac)), I still have never seen [the prompt](https://raw.githubusercontent.com/kvic-z/SsdPmEnabler/main/New_Security_and%20Privacy_in_BigSur.png).

I did also find #5, found it very helpful, it seemed awfully similar because I too am seeing:
```
  Signature Validation Errors:	Kext signature validation error code -67050
```

But … it didn't help.

# Root cause found: `arm64e` support
I finally found the root cause:

```
admin@mist Extensions % sudo kextunload SsdPmEnabler.kext
Password:
Executing: /usr/bin/kmutil unload -p /Library/Extensions/SsdPmEnabler.kext
Error Domain=KMErrorDomain Code=3 "Error occurred unloading extensions: Missing extension with identifier com.ZLab.SsdPmEnabler : Incompatible architecture: Binary is for x86_64, but needed arch arm64e" UserInfo={NSLocalizedDescription=Error occurred unloading extensions: Missing extension with identifier com.ZLab.SsdPmEnabler : Incompatible architecture: Binary is for x86_64, but needed arch arm64e}
```

So obvious in hindsight! 🙈

# Recompiling for `arm64e`

I figured I'd just recompile this for `arm64e`, but … the source code is not available. Any chance you could compile it for Apple silicon too? 🙏

**Comment by wimleers** [comment]
Here's another KEXT project, which was able to simply recompile for `arm64e`: https://github.com/integralpro/nosleep/issues/52, like so:

```
xcodebuild VALID_ARCHS="x86_64 arm64e" CODE_SIGN_IDENTITY="-" -sdk macosx -configuration Release -target TARGETNAME
```

Could you give that a try? 🤞

**Comment by wimleers** [comment]
@kvic-z I see you responded to #21 — I'm eagerly but patiently looking forward to your response here too 😊

**Comment by herb2k** [comment]
Out of curiosity, why do you need this compiled for Apple Silicon? This kext is primarily useful for improving power consumption with 3rd party NVMe drives on machines that can have the stock Apple SSD replaced, which are all intel only.

**Comment by wimleers** [comment]
> Out of curiosity, why do you need this compiled for Apple Silicon? This kext is primarily useful for improving power consumption with 3rd party NVMe drives on machines that can have the stock Apple SSD replaced, which are all intel only.

Thank you so much for the reply! 😊

I have a M1 Mac Mini as a very energy-efficient home server. It idles at 4 Watt! (For back-ups, homebridge.io and software development from my iPad.)

I added an NVME drive via Thunderbolt. This consumes an additional 4 Watt! 🤯🙃 Even though I picked an energy-efficient one.

Because: macOS won’t make it enter its lower power states. That is where this wonderful KEXT comes in 🤓

So: this would cut my home server’s energy use in half!

**Comment by herb2k** [comment]
> > Out of curiosity, why do you need this compiled for Apple Silicon? This kext is primarily useful for improving power consumption with 3rd party NVMe drives on machines that can have the stock Apple SSD replaced, which are all intel only.
> 
> Thank you so much for the reply! 😊
> 
> I have a M1 Mac Mini as a very energy-efficient home server. It idles at 4 Watt! (For back-ups, homebridge.io and software development from my iPad.)
> 
> I added an NVME drive via Thunderbolt. This consumes an additional 4 Watt! 🤯🙃 Even though I picked an energy-efficient one.
> 
> Because: macOS won’t make it enter its lower power states. That is where your wonderful KEXT comes in 🤓
> 
> So: this would cut my home server’s energy use in half!

Ah, very interesting use case. I'm not sure this kext will improve upon that... depends what and how the author is identifying/applying/enabling the PM states on the PCIe ports for the SSD. 

Also keep in mind that the M1 architecture "may" be different from typical intel-based platforms and not support this functionality over thunderbolt (I'm not an expert in this area, but suspect some compatibility issues may occur)

Anyways, good luck and I hope that kvic-z replies :)

**Comment by wimleers** [comment]
It should work exactly the same: Thunderbolt just exposes PCI Express lanes externally roughly speaking.

Some related links:
- https://developer.apple.com/documentation/pcidriverkit/creating_custom_pcie_drivers_for_thunderbolt_devices
- https://www.sonnettech.com/product/echo-express-sel/overview.html

But … yes, let’s wait and see. I’m very hopeful that all we need is a simple recompilation 😊🤞

**Comment by kvic-z** [comment]
Frankly I was also puzzled a bit by the need. And cheerfully learned Thunderbolt idles with high wattage when compared to M1. Okay, a couple of points:

First of all, 4W isn't a lot but seems bad when compared to M1 Mini's idle wattage. This can't be due to the SSD but rather the Thunderbolt enclosure itself. So very likely you're dealing with idle power reduction over Thunderbolt bus not the PCIe it tunnels.

While 4W isn't a lot, if it's connected to a MacBook on battery, it's still a power hog. So I'm quite surprised vendors and Apple haven't done anything to reduce it. What's idle wattage when the enclosure is connected to a MacBook?

If it's way lower than 4W, then the low hanging fruit would be to replicate some of the MacBook's settings on M1 mini. If still 4W, then the challenge would be to look into Thunderbolt which is interesting in itself but not in the scope of this project unfortunately.

**Comment by wimleers** [comment]
First of all: thank you so much for your response, @kvic-z! 😊 

> While 4W isn't a lot, if it's connected to a MacBook on battery, it's still a power hog. So I'm quite surprised vendors and Apple haven't done anything to reduce it. 

I'm surprised too 🙈 😬 

> What's idle wattage when the enclosure is connected to a MacBook?

What way would you like me to measure this?

> This can't be due to the SSD but rather the Thunderbolt enclosure itself. 

Based on this output, I think it can be?

```
admin@mist ~ % smartctl -x /dev/disk4
smartctl 7.2 2020-12-30 r5155 [Darwin 21.2.0 arm64] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       INTEL SSDPEKNW020T8
Serial Number:                      <snip>
Firmware Version:                   002C
PCI Vendor/Subsystem ID:            0x8086
IEEE OUI Identifier:                0x5cd2e4
Controller ID:                      1
NVMe Version:                       1.3
Number of Namespaces:               1
Local Time is:                      Thu Jan 13 21:14:31 2022 CET
Firmware Updates (0x14):            2 Slots, no Reset required
Optional Admin Commands (0x0017):   Security Format Frmw_DL Self_Test
Optional NVM Commands (0x005f):     Comp Wr_Unc DS_Mngmt Wr_Zero Sav/Sel_Feat Timestmp
Log Page Attributes (0x0f):         S/H_per_NS Cmd_Eff_Lg Ext_Get_Lg Telmtry_Lg
Maximum Data Transfer Size:         32 Pages
Warning  Comp. Temp. Threshold:     77 Celsius
Critical Comp. Temp. Threshold:     80 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     5.50W       -        -    0  0  0  0        0       0
 1 +     3.60W       -        -    1  1  1  1        0       0
 2 +     2.60W       -        -    2  2  2  2        0       0
 3 -   0.0300W       -        -    3  3  3  3     5000    5000
 4 -   0.0040W       -        -    4  4  4  4     5000    9000

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        35 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    0%
Data Units Read:                    22,296 [11.4 GB]
Data Units Written:                 154,017 [78.8 GB]
Host Read Commands:                 136,778
Host Write Commands:                612,206
Controller Busy Time:               6
Power Cycles:                       1,073
Power On Hours:                     649
Unsafe Shutdowns:                   5
Media and Data Integrity Errors:    0
Error Information Log Entries:      0
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0

Error Information (NVMe Log 0x01, 16 of 256 entries)
No Errors Logged
```

I actually don't know how I can get the current NVME power state — that would confirm my theory.

EDIT: P.S.: I'm willing to sponsor this feature. I really want this server to be as energy efficient as possible.

**Comment by wimleers** [comment]
Gentle bump :)

**Comment by kvic-z** [comment]
I'm really not convinced you're on the right track. In lack of a better analogy, seems you're trying to save power in a VM while you should be looking at the host.

My suggestion is same as before. Take a look at this block diagram: https://images.anandtech.com/doci/16333/jhl8540bd.png.

Start from Thunderbolt PHY and link controller first, and perhaps dig deeper from there. Linux thunderbolt driver may help. Good luck.
