### ISSUE TITLE
SK Hynix P31 Gold

### ISSUE THREAD

**Issue by kayjeiem** [kvic-z/SsdPmEnabler#21]
I recently installed an SK Hynix P31 Gold 1TB on to my MacBookPro11,5. The installation and setup went well. Everything works well even sleep/wake. No crashes or anything. Based on the recommendations from Macrumors I landed on this kext which i installed following the instructions given. The kext is loaded and running well but it appears to have no impact on the P31 since its idling at between .15A to .25A My question is does this work on the P31? coz i haven't seen it listed on the compatible SSDs yet in the forums guys have mentioned its working.

**Comment by kvic-z** [comment]
MBP11,5 should be fine with this kext. P31 will be idle around 0.10A "out of box" (without any kexts) and less than 0.10A with ssdpmEnabler. These numbers are based from previous reports from other users and Tomshardware's tests. There are two working reports in [Confirmed Working Models](https://github.com/kvic-z/SsdPmEnabler/wiki/Confirmed-working-Mac-models). 

It seems something else is going on inside your machine 'cos I think 0.15A idle is a bit on the high side even "out of box". Or manufacturers could switch compatible components that yield variation in idle power "out of box".

**Comment by kayjeiem** [comment]
Hmm ok. I'll keep checking. Perhaps there's something running in the background. Now it's stabilized at around .08A
