### ISSUE TITLE
KEXT not loaded anymore: Kext signature validation error code -67050

### ISSUE THREAD

**Issue by porg** [kvic-z/SsdPmEnabler#5]
## In January and February
- SsdPmEnabler ran wonderfully and has reduced wattage significantly as reported in #3

## In the last days (more/less in March)
- I noticed significantly lower battery runtimes.
- As I got skeptical today checked wattage with iStats Menus and saw:
  - ~217 mA when idle
  - ~400 mA when system or user-apps is working a bit (though no heavy load such as a speedtest with sustained read/write)
- Why is that significantly higher all of a sudden?

## Checked the following
- System Information > Software > Extensions > SsdPmEnabler
```
SsdPmEnabler:
  Version:	0.1.1
  Last Modified:	23.01.21, 21:02
  Bundle ID:	com.ZLab.SsdPmEnabler
  Notarised:	No
  Loaded:	No
  Obtained from:	Unknown
  Kind:	Intel
  Architectures:	x86_64
  64-Bit (Intel):	Yes
  Location:	/Library/Extensions/SsdPmEnabler.kext
  Kext Version:	0.1.1
  Loadable:	No
  Signature Validation Errors:	Kext signature validation error code -67050
  Dependencies:	Satisfied
  Signed by:	Unknown
```

- System Preferences > Security > General:
  - Shows neither a KEXT warning
  - Nor a possibility "I trust it, please load it" as it did upon initial installation

## What may be different? What may has changed?
1. I am meanwhile on macOS 11.2.1 and firmware 430.0.0.0.0
  - as opposed to macOS 11.1 and firmware Firmware 429.0.0.0 when having reported #3
2. After some restarts or when installing or dropping new .app bundles to /Applications I noticed that:
  - `syspolicyd` ran quite CPU intensively some times
  - `trustd` made some network connections as noticed by [Little Snitch](https://obdev.at/littlesnitch/) according to which:
> "Trust Daemon” is a macOS system process that is responsible for evaluating the validity of digital certificates that are used for encryption and security features.

### My suspicions
- Ad 1: As I do not recall when I noticed the wattage change, and my iStats trial ran out (no data graph anymore), I cannot establish whether the wattage change and the macOS/firmware upgrade correlate.
- Ad 2: Meanwhile more people have SsdPmEnabler.kext installed and via `trustd/syspolicyd` this information reached Apple's servers, and they classified it as suspicious, hence "Kext signature validation error code -67050".

## What else I will try
- I leave this as a bug report, as this itself already qualifies as a bug.
- As soon as I get extra time I will try some more workarounds:
  - Upgrade to macOS 11.2.3 (possible accompanied with a firmware upgrade) and see whether that resolves it.
  - Reinstalling SsdPmEnabler.kext, checking System Preferences again to manually trust the KEXT.

## Followup
- If someone has already some guidance and hence responds, very appreciated!
- Else simply await my report on my other userland fixes/workaround attempts.

Regards, porg

**Comment by herb2k** [comment]
Apple will not allow signatures of 3rd party kexts (this is in kvic-z's instructions). 

I am on 11.2.3 (MacBookPro 12,1, FW 426.0.0.0) and it continues to load properly, despite the -67050 code:

```
SsdPmEnabler:

  Version:	0.1.1
  Last Modified:	2021-02-06, 7:45 PM
  Bundle ID:	com.ZLab.SsdPmEnabler
  Notarized:	No
  Loaded:	Yes
  Obtained from:	Unknown
  Kind:	Intel
  Architectures:	x86_64
  64-Bit (Intel):	Yes
  Location:	/Library/Extensions/SsdPmEnabler.kext
  Kext Version:	0.1.1
  Load Address:	18446743522380886000
  Loadable:	No
  Signature Validation Errors:	Kext signature validation error code -67050
  Dependencies:	Satisfied
  Signed by:	Unknown


```
I suggest trying to remove the kext, rebuild the kextcache and then reinstall after a couple of reboots. You should receive a prompt under Security & Privacy to grant the kext permissions to load.

**Comment by porg** [comment]
1. I will try re-installing according to the official instructions.
2. This my report just indicates that sadly SsdPmEnabler:
  - is not: "install once, then don't worry about it anymore"
  - but rather: "install once, and time and time again re-apply, as the system works against it and breaks it here & then"

**Comment by porg** [comment]
## Reinstallation failed

``` zsh
# Proof that SsdPmEnabler is not loaded
➜  ~ log show --style syslog --last boot | grep \(SsdPmEnabler
# No output means it's not loaded.

## Uninstallation according to manual
➜  ~ cd /Library/Extensions
➜  Extensions sudo kextunload SsdPmEnabler.kext
Password:
Executing: /usr/bin/kmutil unload -p /Library/Extensions/SsdPmEnabler.kext
Error Domain=KMErrorDomain Code=3 "Error occurred unloading extensions: Missing extension with identifier com.ZLab.SsdPmEnabler : Authenticating extension failed: Kext com.ZLab.SsdPmEnabler v0.1.1 in executable kext bundle com.ZLab.SsdPmEnabler at /private/var/db/KernelExtensionManagement/Staging/com.ZLab.SsdPmEnabler.EBlmaX/SsdPmEnabler.kext:

Authenticating extension failed: Bad code signature" UserInfo={NSLocalizedDescription=Error occurred unloading extensions: Missing extension with identifier com.ZLab.SsdPmEnabler : Authenticating extension failed: Kext com.ZLab.SsdPmEnabler v0.1.1 in executable kext bundle com.ZLab.SsdPmEnabler at /private/var/db/KernelExtensionManagement/Staging/com.ZLab.SsdPmEnabler.EBlmaX/SsdPmEnabler.kext:

Authenticating extension failed: Bad code signature}

# That kextunload does nothing is not surprising as the KEXT was not loaded
# But the other errors seems to be a consequence/side-effect of the signature issues I assume-

➜  Extensions sudo rm -rf SsdPmEnabler.kext


## Re-installation according to manual
➜  Extensions sudo cp -R ~/Downloads/SsdPmEnabler.kext /Library/Extensions
# No security dialogue popped up!
# The file was indeed copied. Checked in Finder: CMD-I shows version "0.1.1" and copyright "kvic".


## Other checks
# System Preferences > Security > General: Shows no KEXT info/actions.
# Reboot
# System Preferences > Security > General: Shows still no KEXT info/actions!
```

**Comment by herb2k** [comment]
This is a basic step, but did you disable KEXT signing? I have noticed on macOS upgrades, SIP occasionally re-enables itself. 

Reboot into Recovery Mode, open up terminal and enter:

`csrutil enable --without kext`

Screenshot of the output from csrutil status from my system, below:

```
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	**Kext Signing: disabled**
	Filesystem Protections: enabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
```

**Comment by porg** [comment]
@herb2k you nailed it! Yes!

## Checked my status as of now
``` bash
$ csrutil status
System Integrity Protection status: enabled.
```
Ok so some event or action has definitly re-enabled SIP!


## Rebooted into recovery, ran:
```
$ csrutil enable --without kext
```

## Checked status again now
```
$ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: enabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```
Ok SIP on, except for KEXTs. As we wanted.

Performed entire re-installation again
- UI popup got triggered!
- Went to SysPrefs. Acknowledged that I trust the KEXT developers.
- System needs restart. Ok? --> OK. Restart.

## Checking status after reboot

### System Information
Software > Extensions > SsdPmEnabler: **Loaded: Yes**
```
SsdPmEnabler:

  Version:	0.1.1
  Last Modified:	18.03.21, 22:00
  Bundle ID:	com.ZLab.SsdPmEnabler
  Notarised:	No
  Loaded:	Yes
  Obtained from:	Unknown
  Kind:	Intel
  Architectures:	x86_64
  64-Bit (Intel):	Yes
  Location:	/Library/Extensions/SsdPmEnabler.kext
  Kext Version:	0.1.1
  Load Address:	18446743522381152000
  Loadable:	No
  Signature Validation Errors:	Kext signature validation error code -67050
  Dependencies:	Satisfied
  Signed by:	Unknown
```

### Checking syslog
```
$ log show --style syslog --last boot | grep \(SsdPmEnabler
```
Shows the output which proves that it's loaded according to the manual.

## Checking iStat Menus
- About 5 minutes after boot (where more heavy I/O) happens,
- idle wattage is now again down to 1-20 mA. **Halleluja!**

# Followup
- Before we close it, we should try to isolate the cause and update the documentation / FAQ accordingly!
- I thought again what events could have caused it:
1. macOS 11.1->11.2.1- and Firmware upgrade 429.0.0.0->430.0.0.0
--> If that's indeed the cause, then many other users would need to report that too. Don't think so.
2. Once booted into Recovery, and ran Disk Utility > First Aid on my internal SSD.
--> Is part of the occassional monitoring/maintenance. Less common, but still some would have already fell into that.
3. As a test scenario I ran icloud.com/find in the web browser and locked my Mac remotely.
--> This is likely the cause, as it's quite a low level and thorough locking and unlocking process, probably also involving a SIP reset.
- In the web browser I had to define a 6-digit locking code.
- With a bit delay, but then immediately the Mac shut down. If a criminal was in front of the Mac s/he would have had no time to interrupt the shutdown or take note of anything on screen, as this really happened instantly.
- When rebooting the firmware asked for a firmware password. I used the 6-digit key I had set.
- Then it booted into macOS Preboot. Asked again for an unlocking PW. Used the 6-digit key again.
- Then it booted into macOS and asked for my normal password.
- In the course of this whole procedure it is not unlikely that it also reset SIP.

@kvic-z and @herb2k 
Please confirm my suspicions and if so adapt the FAQs accordingly.
If you need an editorial idea, I as an interested user would favor roughly that structure:
- SsdPmEnabler can sometimes stop working, possible reasons: SIP got reset to being fully enabled.
- Possible reasons for SIP resets are: <Plausible cause1, cause2, …>
- How to check SIP status. If fully enabled: How to re-enable (--> anchor-link in manual)

**Comment by gazzar** [comment]
Just wanted to say thank you; I had the same issue after installing a 512GB Crucial P2 in my Early 2014 MacBookAir6,1 in Big Sur. Following this enabled me to get SsdPmEnabler installed.

**Comment by porg** [comment]
@gazzar glad that this lengthy and detailed writeup of a very complex investigation could help someone else finally! 👍

**Comment by porg** [comment]
✅ Closing
* Meanwhile this knowhow was integrated into the FAQ:
https://github.com/kvic-z/SsdPmEnabler#if-ssdpmenablerkext-is-not-loaded-anymore
